export const LP_PAGE_SIZE = 20;
export const COMMENT_PAGE_SIZE = 10;
export const SCROLL_THRESHOLD_PX = 300;
export const SCROLL_THROTTLE_MS = 1000;

export const SKELETON_LP_GRID_COUNT = LP_PAGE_SIZE;
export const SKELETON_LP_FETCH_MORE_COUNT = 10;
export const SKELETON_COMMENT_INITIAL_COUNT = 5;
export const SKELETON_COMMENT_FETCH_MORE_COUNT = 3;
